package com.paodekuai.analyzer;

import android.app.*;import android.content.*;import android.graphics.Color;import android.media.projection.MediaProjectionManager;import android.net.Uri;import android.os.*;import android.provider.Settings;import android.view.*;import android.widget.*;
import com.paodekuai.analyzer.prefs.AppSettings;import com.paodekuai.analyzer.service.CaptureService;

/** Single control/settings screen. Once started, the foreground service owns the whole live lifecycle. */
public final class MainActivity extends Activity {
    private static final int REQ_CAPTURE=4101;private Switch auto,overlay,advisor,audit;private SeekBar budget;private TextView budgetText,status;private Spinner topK,first;private Button start,stop,overlayPermission;private BroadcastReceiver receiver;
    @Override public void onCreate(Bundle b){super.onCreate(b);buildUi();load();registerStatus();refreshPermissions();}
    private void buildUi(){ScrollView sv=new ScrollView(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(20),dp(18),dp(28));root.setBackgroundColor(Color.WHITE);sv.addView(root);
        TextView title=t("跑得快分析器",26,true);root.addView(title);TextView sub=t("Android Live · 自动识别 / Tracker / Advisor / Overlay",14,false);sub.setTextColor(Color.DKGRAY);root.addView(sub,lpTop(6));
        status=t("状态：未运行",15,true);status.setTextColor(0xFF14532D);root.addView(status,lpTop(18));
        overlayPermission=new Button(this);overlayPermission.setText("授予悬浮窗权限");overlayPermission.setOnClickListener(v->requestOverlay());root.addView(overlayPermission,lpTop(10));
        root.addView(section("运行"),lpTop(18));auto=sw("自动识别新牌局",true);overlay=sw("显示 Overlay",true);advisor=sw("轮到我时自动计算推荐",true);audit=sw("保存运行日志",true);root.addView(auto);root.addView(overlay);root.addView(advisor);root.addView(audit);
        root.addView(section("搜索"),lpTop(16));budgetText=t("搜索预算：500 ms",14,false);root.addView(budgetText);budget=new SeekBar(this);budget.setMax(29);budget.setProgress(4);budget.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar s,int p,boolean f){budgetText.setText("搜索预算："+budgetMs()+" ms");}public void onStartTrackingTouch(SeekBar s){}public void onStopTrackingTouch(SeekBar s){}});root.addView(budget);
        LinearLayout r1=new LinearLayout(this);r1.setOrientation(LinearLayout.HORIZONTAL);r1.addView(t("显示候选：",14,false),new LinearLayout.LayoutParams(0,-2,.42f));topK=new Spinner(this);topK.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"Top 1","Top 2","Top 3","Top 4","Top 5"}));r1.addView(topK,new LinearLayout.LayoutParams(0,-2,.58f));root.addView(r1);
        root.addView(section("牌局"),lpTop(16));LinearLayout r2=new LinearLayout(this);r2.setOrientation(LinearLayout.HORIZONTAL);r2.addView(t("首出识别：",14,false),new LinearLayout.LayoutParams(0,-2,.42f));first=new Spinner(this);first.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"自动（推荐）","我先出","对手先出"}));r2.addView(first,new LinearLayout.LayoutParams(0,-2,.58f));root.addView(r2);
        TextView note=t("开始后只需切回游戏。服务会持续等待新局、自动识别 16 张手牌、跟踪出牌，并在你的回合更新悬浮提示。停止后立即结束屏幕捕获和分析。",13,false);note.setTextColor(Color.DKGRAY);root.addView(note,lpTop(14));
        LinearLayout buttons=new LinearLayout(this);buttons.setOrientation(LinearLayout.HORIZONTAL);start=new Button(this);start.setText("开始分析");start.setOnClickListener(v->begin());buttons.addView(start,new LinearLayout.LayoutParams(0,dp(52),1));stop=new Button(this);stop.setText("结束分析");stop.setOnClickListener(v->stopServiceNow());LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(0,dp(52),1);bp.leftMargin=dp(10);buttons.addView(stop,bp);root.addView(buttons,lpTop(20));
        TextView privacy=t("本地处理：屏幕帧、牌局状态和推荐均在设备上处理；默认不上传。",12,false);privacy.setTextColor(Color.GRAY);root.addView(privacy,lpTop(14));setContentView(sv);}
    private void begin(){save();if(overlay.isChecked()&&!Settings.canDrawOverlays(this)){requestOverlay();status.setText("状态：请先允许悬浮窗，然后再点开始");return;}MediaProjectionManager m=(MediaProjectionManager)getSystemService(MEDIA_PROJECTION_SERVICE);status.setText("状态：等待屏幕录制授权");startActivityForResult(m.createScreenCaptureIntent(),REQ_CAPTURE);}
    @Override protected void onActivityResult(int req,int res,Intent data){super.onActivityResult(req,res,data);if(req!=REQ_CAPTURE)return;if(res!=RESULT_OK||data==null){status.setText("状态：未授权屏幕录制");return;}Intent s=new Intent(this,CaptureService.class).setAction(CaptureService.ACTION_START);s.putExtra(CaptureService.EXTRA_RESULT_CODE,res);s.putExtra(CaptureService.EXTRA_RESULT_DATA,data);if(Build.VERSION.SDK_INT>=26)startForegroundService(s);else startService(s);status.setText("状态：正在启动…可切回游戏");}
    private void stopServiceNow(){Intent s=new Intent(this,CaptureService.class).setAction(CaptureService.ACTION_STOP);startService(s);}
    private void requestOverlay(){Intent i=new Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION,Uri.parse("package:"+getPackageName()));startActivity(i);}
    private void registerStatus(){receiver=new BroadcastReceiver(){@Override public void onReceive(Context c,Intent i){String st=i.getStringExtra("state"),tx=i.getStringExtra("text");status.setText("状态："+(tx==null?st:tx));}};IntentFilter f=new IntentFilter(CaptureService.ACTION_STATUS);if(Build.VERSION.SDK_INT>=33)registerReceiver(receiver,f,Context.RECEIVER_NOT_EXPORTED);else registerReceiver(receiver,f);}
    @Override protected void onResume(){super.onResume();refreshPermissions();}
    private void refreshPermissions(){boolean ok=Settings.canDrawOverlays(this);overlayPermission.setText(ok?"悬浮窗权限：已允许":"授予悬浮窗权限");overlayPermission.setEnabled(!ok);}
    private void load(){AppSettings s=AppSettings.load(this);auto.setChecked(s.autoDetect);overlay.setChecked(s.overlayEnabled);advisor.setChecked(s.advisorEnabled);audit.setChecked(s.keepAudit);budget.setProgress(Math.max(0,Math.min(29,(s.searchBudgetMs-100)/100)));topK.setSelection(s.topK-1);first.setSelection(s.firstPlayer<0?0:(s.firstPlayer==0?1:2));budgetText.setText("搜索预算："+budgetMs()+" ms");}
    private void save(){int fp=first.getSelectedItemPosition()==0?-1:(first.getSelectedItemPosition()==1?0:1);new AppSettings(auto.isChecked(),overlay.isChecked(),advisor.isChecked(),audit.isChecked(),budgetMs(),topK.getSelectedItemPosition()+1,fp).save(this);}
    private int budgetMs(){return 100+budget.getProgress()*100;}
    private Switch sw(String s,boolean v){Switch x=new Switch(this);x.setText(s);x.setTextSize(15);x.setChecked(v);x.setPadding(0,dp(5),0,dp(5));return x;}
    private TextView section(String s){TextView x=t(s,16,true);x.setTextColor(0xFF1D4ED8);return x;}private TextView t(String s,int size,boolean bold){TextView x=new TextView(this);x.setText(s);x.setTextSize(size);x.setTextColor(0xFF111827);if(bold)x.setTypeface(null,1);return x;}private LinearLayout.LayoutParams lpTop(int m){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.topMargin=dp(m);return p;}private int dp(int x){return (int)(x*getResources().getDisplayMetrics().density+.5f);}
    @Override protected void onDestroy(){save();if(receiver!=null)try{unregisterReceiver(receiver);}catch(Exception ignored){}super.onDestroy();}
}
