package com.paodekuai.analyzer.advisor;

import com.paodekuai.analyzer.tracker.GameTracker;
import com.paodekuai.analyzer.tracker.RuleEngine;
import java.util.*;

/** Two-player rank-only SO-ISMCTS port of the Python reference search model. */
final class SoIsmctsEngine {
    static final class Candidate {final String action;final int visits,availability;final double score;Candidate(String a,int v,int av,double s){action=a;visits=v;availability=av;score=s;}}
    static final class Result {final List<Candidate> actions;final int iterations,treeNodes,reservoir,attempts,cutoffs;final long elapsedMs;Result(List<Candidate>a,int i,int n,int r,int at,long ms,int c){actions=a;iterations=i;treeNodes=n;reservoir=r;attempts=at;elapsedMs=ms;cutoffs=c;}}
    static final class Snapshot {
        final String ownHand;final int opponentCards;final RuleEngine.Play target;final Integer targetOwner;final int currentPlayer;final int firstPlayer;final List<GameTracker.Hist> history;
        Snapshot(String h,int o,RuleEngine.Play t,Integer owner,int cp,int fp,List<GameTracker.Hist> hist){ownHand=h;opponentCards=o;target=t;targetOwner=owner;currentPlayer=cp;firstPlayer=fp;history=List.copyOf(hist);}
    }
    private static final class State {
        final String[] hands;final int cp;final RuleEngine.Play target;final Integer leader;final int passes;final Integer winner;
        State(String a,String b,int cp,RuleEngine.Play t,Integer l,int p,Integer w){hands=new String[]{a,b};this.cp=cp;target=t;leader=l;passes=p;winner=w;}
        List<RuleEngine.Play> plays(){List<RuleEngine.Play> p=RuleEngine.legalResponses(hands[cp],target);if(target==null){if(hands[1-cp].length()==1){int highest=-1;for(RuleEngine.Play x:p)if(x.type==RuleEngine.Type.SINGLE)highest=Math.max(highest,x.mainRank);if(highest>=0){List<RuleEngine.Play> f=new ArrayList<>();for(RuleEngine.Play x:p)if(x.type!=RuleEngine.Type.SINGLE||x.mainRank==highest)f.add(x);p=f;}}return p;}return p;}
        List<Action> legal(){List<RuleEngine.Play> p=plays();List<Action> a=new ArrayList<>();for(RuleEngine.Play x:p)a.add(new Action(x));if(target!=null&&p.isEmpty())a.add(Action.PASS);return a;}
        State apply(Action a){if(winner!=null)throw new IllegalStateException("finished");if(a.pass){if(target==null)throw new IllegalArgumentException("pass while leading");int np=passes+1;if(np>=1){if(leader==null)throw new IllegalStateException("leader missing");return new State(hands[0],hands[1],leader,null,null,0,null);}return new State(hands[0],hands[1],1-cp,target,leader,np,null);}String nh=RuleEngine.subtract(hands[cp],a.play.cards);String h0=cp==0?nh:hands[0],h1=cp==1?nh:hands[1];if(nh.isEmpty())return new State(h0,h1,cp,a.play,cp,0,cp);return new State(h0,h1,1-cp,a.play,cp,0,null);}
    }
    private static final class Action {static final Action PASS=new Action();final RuleEngine.Play play;final boolean pass;private Action(){play=null;pass=true;}Action(RuleEngine.Play p){play=p;pass=false;}String label(){return pass?"PASS":play.cards;}String key(){return pass?"P":"A|"+play.type+"|"+play.cards+"|"+play.mainRank+"|"+play.chainLen;}}
    private static final class AStats {final Action a;int visits,availability;final double[] reward={0,0};AStats(Action a){this.a=a;}double mean(int p){return visits==0?0:reward[p]/visits;}}
    private static final class Node {int visits;final Map<String,AStats> actions=new LinkedHashMap<>();}
    private static final class InfoKey {final int cp;final String own;final int n0,n1;final String target;final Integer leader;final int passes;final Integer winner;InfoKey(State s){cp=s.cp;own=s.hands[0];n0=s.hands[0].length();n1=s.hands[1].length();target=s.target==null?"-":s.target.type+":"+s.target.cards+":"+s.target.mainRank+":"+s.target.chainLen;leader=s.leader;passes=s.passes;winner=s.winner;}public boolean equals(Object o){if(!(o instanceof InfoKey k))return false;return cp==k.cp&&n0==k.n0&&n1==k.n1&&passes==k.passes&&Objects.equals(own,k.own)&&Objects.equals(target,k.target)&&Objects.equals(leader,k.leader)&&Objects.equals(winner,k.winner);}public int hashCode(){return Objects.hash(cp,own,n0,n1,target,leader,passes,winner);}}
    private final Snapshot snap;private final Random rng;private final int reservoirSize=48;
    SoIsmctsEngine(Snapshot s,long seed){snap=s;rng=new Random(seed);}

    Result search(int maxIterations,int budgetMs,double exploration){long start=System.nanoTime(),deadline=start+budgetMs*1_000_000L;Reservoir rr=sampleReservoir(reservoirSize,5000,deadline);if(rr.worlds.isEmpty())return new Result(List.of(),0,0,0,rr.attempts,(System.nanoTime()-start)/1_000_000L,0);
        Map<InfoKey,Node> tree=new HashMap<>();int done=0,cutoffs=0;
        while(done<maxIterations && (done==0 || System.nanoTime()<deadline)){State st=rr.worlds.get(rng.nextInt(rr.worlds.size()));List<Map.Entry<Node,AStats>> path=new ArrayList<>();int depth=0;
            while(st.winner==null&&depth++<80){InfoKey k=new InfoKey(st);Node node=tree.computeIfAbsent(k,x->new Node());List<Action> legal=st.legal();if(legal.isEmpty())break;List<AStats> av=new ArrayList<>();for(Action a:legal){AStats as=node.actions.computeIfAbsent(a.key(),x->new AStats(a));as.availability++;av.add(as);}AStats chosen=select(node,av,st.cp,exploration);path.add(new AbstractMap.SimpleImmutableEntry<>(node,chosen));st=st.apply(chosen.a);if(chosen.visits==0)break;}
            int rd=0;while(st.winner==null&&rd++<120){List<Action> acts=st.legal();if(acts.isEmpty())break;st=st.apply(rolloutPick(st,acts));}
            double[] rewards;if(st.winner!=null){rewards=new double[]{0,0};rewards[st.winner]=1;}else{cutoffs++;double a=Math.exp(-st.hands[0].length()/3.0),b=Math.exp(-st.hands[1].length()/3.0),sum=a+b;rewards=new double[]{a/sum,b/sum};}
            for(var e:path){e.getKey().visits++;AStats as=e.getValue();as.visits++;as.reward[0]+=rewards[0];as.reward[1]+=rewards[1];}done++;}
        State root=rr.worlds.get(0);Node rn=tree.get(new InfoKey(root));List<Candidate> out=new ArrayList<>();if(rn!=null)for(AStats a:rn.actions.values())out.add(new Candidate(a.a.label(),a.visits,a.availability,a.mean(0)));out.sort(Comparator.<Candidate>comparingDouble(x->x.score).thenComparingInt(x->x.visits).thenComparingInt(x->x.availability).thenComparing(x->x.action).reversed());return new Result(out,done,tree.size(),rr.worlds.size(),rr.attempts,(System.nanoTime()-start)/1_000_000L,cutoffs);}
    private AStats select(Node n,List<AStats> a,int player,double c){for(AStats x:a)if(x.visits==0)return x;AStats best=null;double bv=-1e99;for(AStats x:a){double v=x.mean(player)+c*Math.sqrt(Math.log(Math.max(2,x.availability))/(double)x.visits);if(v>bv||(v==bv&&x.a.label().compareTo(best==null?"":best.a.label())<0)){bv=v;best=x;}}return best;}
    private Action rolloutPick(State s,List<Action>a){List<Action> wins=new ArrayList<>();for(Action x:a)if(!x.pass&&x.play.length()==s.hands[s.cp].length())wins.add(x);if(!wins.isEmpty())return wins.get(rng.nextInt(wins.size()));double total=0;double[] w=new double[a.size()];for(int i=0;i<a.size();i++){Action x=a.get(i);w[i]=x.pass?.7:1+.65*x.play.length()+.03*(16-Math.min(x.play.mainRank,16));total+=Math.max(.05,w[i]);}double q=rng.nextDouble()*total,acc=0;for(int i=0;i<a.size();i++){acc+=Math.max(.05,w[i]);if(q<=acc)return a.get(i);}return a.get(a.size()-1);}
    private static final class Reservoir {final List<State> worlds;final int attempts;Reservoir(List<State>w,int a){worlds=w;attempts=a;}}
    private Reservoir sampleReservoir(int target,int max,long deadline){List<State>w=new ArrayList<>();int at=0;while(w.size()<target&&at++<max&&System.nanoTime()<deadline){String opp=sampleCurrentOpponent();if(opp==null)continue;if(!historyConsistent(opp))continue;w.add(new State(snap.ownHand,opp,snap.currentPlayer,snap.target,snap.targetOwner,0,null));}return new Reservoir(w,at);}
    private String sampleCurrentOpponent(){Map<Integer,Integer> pool=new TreeMap<>();for(int r=3;r<=15;r++)pool.put(r,4);StringBuilder played=new StringBuilder();for(GameTracker.Hist h:snap.history)if(h.action!=null)played.append(h.action.cards);if(!remove(pool,snap.ownHand)||!remove(pool,played.toString()))return null;List<Character>x=new ArrayList<>();for(var e:pool.entrySet())for(int i=0;i<e.getValue();i++)x.add(RuleEngine.text(e.getKey()));if(x.size()<snap.opponentCards)return null;Collections.shuffle(x,rng);StringBuilder b=new StringBuilder();for(int i=0;i<snap.opponentCards;i++)b.append(x.get(i));return RuleEngine.sortText(b.toString());}
    private boolean historyConsistent(String currentOpp){if(snap.history.isEmpty())return true;String ownInitial=reconstructInitial(0,snap.ownHand),oppInitial=reconstructInitial(1,currentOpp);State st=new State(ownInitial,oppInitial,snap.firstPlayer,null,null,0,null);try{for(GameTracker.Hist h:snap.history){if(st.cp!=h.player)return false;Action wanted=h.action==null?Action.PASS:new Action(h.action);boolean found=false;for(Action a:st.legal())if(a.key().equals(wanted.key())){wanted=a;found=true;break;}if(!found)return false;st=st.apply(wanted);}return st.hands[0].equals(snap.ownHand)&&st.hands[1].length()==snap.opponentCards&&st.cp==snap.currentPlayer&&samePlay(st.target,snap.target)&&Objects.equals(st.leader,snap.targetOwner);}catch(Exception e){return false;}}
    private String reconstructInitial(int player,String current){StringBuilder b=new StringBuilder(current);for(GameTracker.Hist h:snap.history)if(h.player==player&&h.action!=null)b.append(h.action.cards);return RuleEngine.sortText(b.toString());}
    private static boolean samePlay(RuleEngine.Play a,RuleEngine.Play b){if(a==null||b==null)return a==b;return a.type==b.type&&a.cards.equals(b.cards)&&a.mainRank==b.mainRank&&a.chainLen==b.chainLen;}
    private static boolean remove(Map<Integer,Integer>p,String s){for(char c:s.toCharArray()){int r=RuleEngine.rank(c),n=p.getOrDefault(r,0)-1;if(n<0)return false;if(n==0)p.remove(r);else p.put(r,n);}return true;}
}
