package com.paodekuai.analyzer.service;

import android.app.*;import android.content.*;import android.graphics.*;import android.hardware.display.*;import android.media.*;import android.media.projection.*;import android.os.*;import android.util.*;import android.view.*;
import com.paodekuai.analyzer.capture.FrameNormalizer;import com.paodekuai.analyzer.overlay.OverlayController;import com.paodekuai.analyzer.prefs.AppSettings;import com.paodekuai.analyzer.runtime.LiveAnalyzerRuntime;import com.paodekuai.analyzer.vision.TemplateBank;
import org.opencv.android.*;import org.opencv.core.*;import org.opencv.imgproc.Imgproc;import java.nio.*;import java.util.concurrent.*;import java.util.concurrent.atomic.AtomicBoolean;

public final class CaptureService extends Service {
    public static final String ACTION_START="com.paodekuai.analyzer.START",ACTION_STOP="com.paodekuai.analyzer.STOP",ACTION_STATUS="com.paodekuai.analyzer.STATUS";
    public static final String EXTRA_RESULT_CODE="resultCode",EXTRA_RESULT_DATA="resultData";private static final String CH="pdk_capture";private static final int NID=2401;
    private HandlerThread imageThread;private Handler imageHandler;private ExecutorService processing;private final AtomicBoolean frameBusy=new AtomicBoolean(false);private MediaProjection projection;private VirtualDisplay display;private ImageReader reader;private LiveAnalyzerRuntime runtime;private OverlayController overlay;private FrameNormalizer normalizer;

    @Override public void onCreate(){super.onCreate();createChannel();processing=Executors.newSingleThreadExecutor(r->{Thread t=new Thread(r,"pdk-vision");t.setDaemon(true);return t;});normalizer=new FrameNormalizer();}
    @Override public int onStartCommand(Intent i,int flags,int id){String a=i==null?null:i.getAction();if(ACTION_STOP.equals(a)){stopEverything("已停止");return START_NOT_STICKY;}if(ACTION_START.equals(a)){startForeground(NID,notification("正在启动分析…"));try{startCapture(i);}catch(Throwable e){broadcast("ERROR",e.toString());stopEverything("启动失败");}}return START_NOT_STICKY;}
    private synchronized void startCapture(Intent i) throws Exception {if(projection!=null)return;if(!OpenCVLoader.initLocal())throw new IllegalStateException("OpenCV init failed");AppSettings settings=AppSettings.load(this);overlay=new OverlayController(this);if(settings.overlayEnabled)overlay.show();TemplateBank hb=TemplateBank.load(getAssets(),"hand_templates",false),tb=TemplateBank.load(getAssets(),"table_templates",true);runtime=new LiveAnalyzerRuntime(this,hb,tb,settings,overlay,(p,s)->{broadcast(p.name(),s);updateNotification(s);});
        Intent data=Build.VERSION.SDK_INT>=33?i.getParcelableExtra(EXTRA_RESULT_DATA,Intent.class):i.getParcelableExtra(EXTRA_RESULT_DATA);int result=i.getIntExtra(EXTRA_RESULT_CODE,Activity.RESULT_CANCELED);if(data==null||result!=Activity.RESULT_OK)throw new IllegalArgumentException("缺少屏幕录制授权");MediaProjectionManager m=(MediaProjectionManager)getSystemService(MEDIA_PROJECTION_SERVICE);projection=m.getMediaProjection(result,data);if(projection==null)throw new IllegalStateException("MediaProjection unavailable");projection.registerCallback(new MediaProjection.Callback(){@Override public void onStop(){stopEverything("屏幕录制已结束");}},new Handler(Looper.getMainLooper()));
        DisplayMetrics dm=getResources().getDisplayMetrics();int w=Math.max(dm.widthPixels,dm.heightPixels),h=Math.min(dm.widthPixels,dm.heightPixels),dpi=dm.densityDpi;reader=ImageReader.newInstance(w,h,PixelFormat.RGBA_8888,3);imageThread=new HandlerThread("pdk-capture");imageThread.start();imageHandler=new Handler(imageThread.getLooper());reader.setOnImageAvailableListener(this::onImage,imageHandler);display=projection.createVirtualDisplay("PDK Analyzer",w,h,dpi,DisplayManager.VIRTUAL_DISPLAY_FLAG_AUTO_MIRROR,reader.getSurface(),null,imageHandler);broadcast("WAITING_FOR_GAME","屏幕捕获已启动");}
    private void onImage(ImageReader r){Image image=null;try{image=r.acquireLatestImage();if(image==null||frameBusy.getAndSet(true))return;Image.Plane p=image.getPlanes()[0];ByteBuffer buf=p.getBuffer();int ps=p.getPixelStride(),rs=p.getRowStride(),pad=rs-ps*image.getWidth(),bw=image.getWidth()+pad/ps;Bitmap wide=Bitmap.createBitmap(bw,image.getHeight(),Bitmap.Config.ARGB_8888);wide.copyPixelsFromBuffer(buf);Bitmap bmp=Bitmap.createBitmap(wide,0,0,image.getWidth(),image.getHeight());wide.recycle();long ts=System.nanoTime();processing.execute(()->{Mat rgba=new Mat(),bgr=new Mat(),canon=null;try{Utils.bitmapToMat(bmp,rgba);Imgproc.cvtColor(rgba,bgr,Imgproc.COLOR_RGBA2BGR);canon=normalizer.normalize(bgr);LiveAnalyzerRuntime rt=runtime;if(rt!=null)rt.onFrame(canon,ts/1e9);}catch(Throwable e){broadcast("ERROR","帧处理失败: "+e.getMessage());}finally{if(canon!=null)canon.release();rgba.release();bgr.release();bmp.recycle();frameBusy.set(false);}});}catch(Throwable e){frameBusy.set(false);}finally{if(image!=null)image.close();}}
    private synchronized void stopEverything(String why){if(runtime!=null){runtime.close();runtime=null;}if(overlay!=null){overlay.hide();overlay=null;}if(display!=null){display.release();display=null;}if(reader!=null){reader.close();reader=null;}MediaProjection old=projection;projection=null;if(old!=null){try{old.stop();}catch(Exception ignored){}}if(imageThread!=null){imageThread.quitSafely();imageThread=null;}broadcast("STOPPED",why);stopForeground(STOP_FOREGROUND_REMOVE);stopSelf();}
    private void broadcast(String state,String text){Intent x=new Intent(ACTION_STATUS).setPackage(getPackageName());x.putExtra("state",state);x.putExtra("text",text);sendBroadcast(x);}
    private void createChannel(){if(Build.VERSION.SDK_INT>=26){NotificationChannel c=new NotificationChannel(CH,"跑得快分析",NotificationManager.IMPORTANCE_LOW);c.setDescription("屏幕分析前台服务");getSystemService(NotificationManager.class).createNotificationChannel(c);}}
    private Notification notification(String text){Intent open=new Intent(this,com.paodekuai.analyzer.MainActivity.class);PendingIntent pi=PendingIntent.getActivity(this,0,open,PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT);Intent stop=new Intent(this,CaptureService.class).setAction(ACTION_STOP);PendingIntent ps=PendingIntent.getService(this,1,stop,PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT);return new Notification.Builder(this,CH).setSmallIcon(android.R.drawable.ic_media_play).setContentTitle("跑得快分析器运行中").setContentText(text).setContentIntent(pi).setOngoing(true).addAction(new Notification.Action.Builder(null,"停止",ps).build()).build();}
    private void updateNotification(String text){getSystemService(NotificationManager.class).notify(NID,notification(text));}
    @Override public void onDestroy(){if(runtime!=null){runtime.close();runtime=null;}if(overlay!=null){overlay.hide();overlay=null;}if(display!=null){display.release();display=null;}if(reader!=null){reader.close();reader=null;}if(imageThread!=null){imageThread.quitSafely();imageThread=null;}if(processing!=null)processing.shutdownNow();super.onDestroy();}
    @Override public android.os.IBinder onBind(Intent i){return null;}
}
